// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: agent.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Hardware      *HardwareInfo          `protobuf:"bytes,3,opt,name=hardware,proto3" json:"hardware,omitempty"`
	Limits        *ResourceLimits        `protobuf:"bytes,4,opt,name=limits,proto3" json:"limits,omitempty"`
	Benchmark     *BenchmarkResult       `protobuf:"bytes,5,opt,name=benchmark,proto3" json:"benchmark,omitempty"`
	UserApiKey    string                 `protobuf:"bytes,6,opt,name=user_api_key,json=userApiKey,proto3" json:"user_api_key,omitempty"`
	CsrPem        []byte                 `protobuf:"bytes,7,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *RegisterRequest) GetHardware() *HardwareInfo {
	if x != nil {
		return x.Hardware
	}
	return nil
}

func (x *RegisterRequest) GetLimits() *ResourceLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *RegisterRequest) GetBenchmark() *BenchmarkResult {
	if x != nil {
		return x.Benchmark
	}
	return nil
}

func (x *RegisterRequest) GetUserApiKey() string {
	if x != nil {
		return x.UserApiKey
	}
	return ""
}

func (x *RegisterRequest) GetCsrPem() []byte {
	if x != nil {
		return x.CsrPem
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	CertPem       []byte                 `protobuf:"bytes,3,opt,name=cert_pem,json=certPem,proto3" json:"cert_pem,omitempty"`
	CaCertPem     []byte                 `protobuf:"bytes,4,opt,name=ca_cert_pem,json=caCertPem,proto3" json:"ca_cert_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterResponse) GetCertPem() []byte {
	if x != nil {
		return x.CertPem
	}
	return nil
}

func (x *RegisterResponse) GetCaCertPem() []byte {
	if x != nil {
		return x.CaCertPem
	}
	return nil
}

type HardwareInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CpuCores       int32                  `protobuf:"varint,1,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	RamGb          float32                `protobuf:"fixed32,2,opt,name=ram_gb,json=ramGb,proto3" json:"ram_gb,omitempty"`
	GpuModel       string                 `protobuf:"bytes,3,opt,name=gpu_model,json=gpuModel,proto3" json:"gpu_model,omitempty"`
	GpuLayersTotal int32                  `protobuf:"varint,4,opt,name=gpu_layers_total,json=gpuLayersTotal,proto3" json:"gpu_layers_total,omitempty"`
	Arch           string                 `protobuf:"bytes,5,opt,name=arch,proto3" json:"arch,omitempty"`
	Os             string                 `protobuf:"bytes,6,opt,name=os,proto3" json:"os,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HardwareInfo) Reset() {
	*x = HardwareInfo{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HardwareInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardwareInfo) ProtoMessage() {}

func (x *HardwareInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardwareInfo.ProtoReflect.Descriptor instead.
func (*HardwareInfo) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *HardwareInfo) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *HardwareInfo) GetRamGb() float32 {
	if x != nil {
		return x.RamGb
	}
	return 0
}

func (x *HardwareInfo) GetGpuModel() string {
	if x != nil {
		return x.GpuModel
	}
	return ""
}

func (x *HardwareInfo) GetGpuLayersTotal() int32 {
	if x != nil {
		return x.GpuLayersTotal
	}
	return 0
}

func (x *HardwareInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *HardwareInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

type ResourceLimits struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent    float32                `protobuf:"fixed32,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	RamPercent    float32                `protobuf:"fixed32,2,opt,name=ram_percent,json=ramPercent,proto3" json:"ram_percent,omitempty"`
	GpuLayers     int32                  `protobuf:"varint,3,opt,name=gpu_layers,json=gpuLayers,proto3" json:"gpu_layers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceLimits) Reset() {
	*x = ResourceLimits{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLimits) ProtoMessage() {}

func (x *ResourceLimits) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLimits.ProtoReflect.Descriptor instead.
func (*ResourceLimits) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ResourceLimits) GetCpuPercent() float32 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ResourceLimits) GetRamPercent() float32 {
	if x != nil {
		return x.RamPercent
	}
	return 0
}

func (x *ResourceLimits) GetGpuLayers() int32 {
	if x != nil {
		return x.GpuLayers
	}
	return 0
}

type BenchmarkResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CpuScore         float32                `protobuf:"fixed32,1,opt,name=cpu_score,json=cpuScore,proto3" json:"cpu_score,omitempty"`
	MemBandwidthGbps float32                `protobuf:"fixed32,2,opt,name=mem_bandwidth_gbps,json=memBandwidthGbps,proto3" json:"mem_bandwidth_gbps,omitempty"`
	GpuTflops        float32                `protobuf:"fixed32,3,opt,name=gpu_tflops,json=gpuTflops,proto3" json:"gpu_tflops,omitempty"`
	CompositeScore   float32                `protobuf:"fixed32,4,opt,name=composite_score,json=compositeScore,proto3" json:"composite_score,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BenchmarkResult) Reset() {
	*x = BenchmarkResult{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BenchmarkResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BenchmarkResult) ProtoMessage() {}

func (x *BenchmarkResult) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BenchmarkResult.ProtoReflect.Descriptor instead.
func (*BenchmarkResult) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *BenchmarkResult) GetCpuScore() float32 {
	if x != nil {
		return x.CpuScore
	}
	return 0
}

func (x *BenchmarkResult) GetMemBandwidthGbps() float32 {
	if x != nil {
		return x.MemBandwidthGbps
	}
	return 0
}

func (x *BenchmarkResult) GetGpuTflops() float32 {
	if x != nil {
		return x.GpuTflops
	}
	return 0
}

func (x *BenchmarkResult) GetCompositeScore() float32 {
	if x != nil {
		return x.CompositeScore
	}
	return 0
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	CpuUsage      float32                `protobuf:"fixed32,2,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	RamUsage      float32                `protobuf:"fixed32,3,opt,name=ram_usage,json=ramUsage,proto3" json:"ram_usage,omitempty"`
	ActiveJobs    int32                  `protobuf:"varint,4,opt,name=active_jobs,json=activeJobs,proto3" json:"active_jobs,omitempty"`
	TokenBalance  float32                `protobuf:"fixed32,5,opt,name=token_balance,json=tokenBalance,proto3" json:"token_balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *HeartbeatRequest) GetRamUsage() float32 {
	if x != nil {
		return x.RamUsage
	}
	return 0
}

func (x *HeartbeatRequest) GetActiveJobs() int32 {
	if x != nil {
		return x.ActiveJobs
	}
	return 0
}

func (x *HeartbeatRequest) GetTokenBalance() float32 {
	if x != nil {
		return x.TokenBalance
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type StreamJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamJobsRequest) Reset() {
	*x = StreamJobsRequest{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamJobsRequest) ProtoMessage() {}

func (x *StreamJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamJobsRequest.ProtoReflect.Descriptor instead.
func (*StreamJobsRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *StreamJobsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type JobPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature     string                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=deadline,proto3" json:"deadline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobPayload) Reset() {
	*x = JobPayload{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobPayload) ProtoMessage() {}

func (x *JobPayload) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobPayload.ProtoReflect.Descriptor instead.
func (*JobPayload) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *JobPayload) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobPayload) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *JobPayload) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *JobPayload) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *JobPayload) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

type JobResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	JobId           string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	AgentId         string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Success         bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Result          []byte                 `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	Error           string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	DurationSeconds float32                `protobuf:"fixed32,6,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *JobResult) Reset() {
	*x = JobResult{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResult) ProtoMessage() {}

func (x *JobResult) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResult.ProtoReflect.Descriptor instead.
func (*JobResult) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *JobResult) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobResult) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *JobResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *JobResult) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *JobResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *JobResult) GetDurationSeconds() float32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x12sharedgpu.agent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbc\x02\n" +
	"\x0fRegisterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12<\n" +
	"\bhardware\x18\x03 \x01(\v2 .sharedgpu.agent.v1.HardwareInfoR\bhardware\x12:\n" +
	"\x06limits\x18\x04 \x01(\v2\".sharedgpu.agent.v1.ResourceLimitsR\x06limits\x12A\n" +
	"\tbenchmark\x18\x05 \x01(\v2#.sharedgpu.agent.v1.BenchmarkResultR\tbenchmark\x12 \n" +
	"\fuser_api_key\x18\x06 \x01(\tR\n" +
	"userApiKey\x12\x17\n" +
	"\acsr_pem\x18\a \x01(\fR\x06csrPem\"~\n" +
	"\x10RegisterResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x19\n" +
	"\bcert_pem\x18\x03 \x01(\fR\acertPem\x12\x1e\n" +
	"\vca_cert_pem\x18\x04 \x01(\fR\tcaCertPem\"\xad\x01\n" +
	"\fHardwareInfo\x12\x1b\n" +
	"\tcpu_cores\x18\x01 \x01(\x05R\bcpuCores\x12\x15\n" +
	"\x06ram_gb\x18\x02 \x01(\x02R\x05ramGb\x12\x1b\n" +
	"\tgpu_model\x18\x03 \x01(\tR\bgpuModel\x12(\n" +
	"\x10gpu_layers_total\x18\x04 \x01(\x05R\x0egpuLayersTotal\x12\x12\n" +
	"\x04arch\x18\x05 \x01(\tR\x04arch\x12\x0e\n" +
	"\x02os\x18\x06 \x01(\tR\x02os\"q\n" +
	"\x0eResourceLimits\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x02R\n" +
	"cpuPercent\x12\x1f\n" +
	"\vram_percent\x18\x02 \x01(\x02R\n" +
	"ramPercent\x12\x1d\n" +
	"\n" +
	"gpu_layers\x18\x03 \x01(\x05R\tgpuLayers\"\xa4\x01\n" +
	"\x0fBenchmarkResult\x12\x1b\n" +
	"\tcpu_score\x18\x01 \x01(\x02R\bcpuScore\x12,\n" +
	"\x12mem_bandwidth_gbps\x18\x02 \x01(\x02R\x10memBandwidthGbps\x12\x1d\n" +
	"\n" +
	"gpu_tflops\x18\x03 \x01(\x02R\tgpuTflops\x12'\n" +
	"\x0fcomposite_score\x18\x04 \x01(\x02R\x0ecompositeScore\"\xad\x01\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\tcpu_usage\x18\x02 \x01(\x02R\bcpuUsage\x12\x1b\n" +
	"\tram_usage\x18\x03 \x01(\x02R\bramUsage\x12\x1f\n" +
	"\vactive_jobs\x18\x04 \x01(\x05R\n" +
	"activeJobs\x12#\n" +
	"\rtoken_balance\x18\x05 \x01(\x02R\ftokenBalance\"#\n" +
	"\x11HeartbeatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\".\n" +
	"\x11StreamJobsRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"\xa7\x01\n" +
	"\n" +
	"JobPayload\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\tR\tsignature\x126\n" +
	"\bdeadline\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\"\xb0\x01\n" +
	"\tJobResult\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x16\n" +
	"\x06result\x18\x04 \x01(\fR\x06result\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12)\n" +
	"\x10duration_seconds\x18\x06 \x01(\x02R\x0fdurationSeconds\"\x15\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xde\x02\n" +
	"\fAgentService\x12U\n" +
	"\bRegister\x12#.sharedgpu.agent.v1.RegisterRequest\x1a$.sharedgpu.agent.v1.RegisterResponse\x12X\n" +
	"\tHeartbeat\x12$.sharedgpu.agent.v1.HeartbeatRequest\x1a%.sharedgpu.agent.v1.HeartbeatResponse\x12U\n" +
	"\n" +
	"StreamJobs\x12%.sharedgpu.agent.v1.StreamJobsRequest\x1a\x1e.sharedgpu.agent.v1.JobPayload0\x01\x12F\n" +
	"\fReportResult\x12\x1d.sharedgpu.agent.v1.JobResult\x1a\x17.sharedgpu.agent.v1.AckBAZ?github.com/lambdawp-567/sharedgpupower/backend/internal/grpc/pbb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_agent_proto_goTypes = []any{
	(*RegisterRequest)(nil),       // 0: sharedgpu.agent.v1.RegisterRequest
	(*RegisterResponse)(nil),      // 1: sharedgpu.agent.v1.RegisterResponse
	(*HardwareInfo)(nil),          // 2: sharedgpu.agent.v1.HardwareInfo
	(*ResourceLimits)(nil),        // 3: sharedgpu.agent.v1.ResourceLimits
	(*BenchmarkResult)(nil),       // 4: sharedgpu.agent.v1.BenchmarkResult
	(*HeartbeatRequest)(nil),      // 5: sharedgpu.agent.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 6: sharedgpu.agent.v1.HeartbeatResponse
	(*StreamJobsRequest)(nil),     // 7: sharedgpu.agent.v1.StreamJobsRequest
	(*JobPayload)(nil),            // 8: sharedgpu.agent.v1.JobPayload
	(*JobResult)(nil),             // 9: sharedgpu.agent.v1.JobResult
	(*Ack)(nil),                   // 10: sharedgpu.agent.v1.Ack
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_agent_proto_depIdxs = []int32{
	2,  // 0: sharedgpu.agent.v1.RegisterRequest.hardware:type_name -> sharedgpu.agent.v1.HardwareInfo
	3,  // 1: sharedgpu.agent.v1.RegisterRequest.limits:type_name -> sharedgpu.agent.v1.ResourceLimits
	4,  // 2: sharedgpu.agent.v1.RegisterRequest.benchmark:type_name -> sharedgpu.agent.v1.BenchmarkResult
	11, // 3: sharedgpu.agent.v1.JobPayload.deadline:type_name -> google.protobuf.Timestamp
	0,  // 4: sharedgpu.agent.v1.AgentService.Register:input_type -> sharedgpu.agent.v1.RegisterRequest
	5,  // 5: sharedgpu.agent.v1.AgentService.Heartbeat:input_type -> sharedgpu.agent.v1.HeartbeatRequest
	7,  // 6: sharedgpu.agent.v1.AgentService.StreamJobs:input_type -> sharedgpu.agent.v1.StreamJobsRequest
	9,  // 7: sharedgpu.agent.v1.AgentService.ReportResult:input_type -> sharedgpu.agent.v1.JobResult
	1,  // 8: sharedgpu.agent.v1.AgentService.Register:output_type -> sharedgpu.agent.v1.RegisterResponse
	6,  // 9: sharedgpu.agent.v1.AgentService.Heartbeat:output_type -> sharedgpu.agent.v1.HeartbeatResponse
	8,  // 10: sharedgpu.agent.v1.AgentService.StreamJobs:output_type -> sharedgpu.agent.v1.JobPayload
	10, // 11: sharedgpu.agent.v1.AgentService.ReportResult:output_type -> sharedgpu.agent.v1.Ack
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
