// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: job.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SubmitterAgentId string                 `protobuf:"bytes,1,opt,name=submitter_agent_id,json=submitterAgentId,proto3" json:"submitter_agent_id,omitempty"`
	Type             string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Llm              *LLMInferencePayload   `protobuf:"bytes,3,opt,name=llm,proto3" json:"llm,omitempty"`
	Async            bool                   `protobuf:"varint,4,opt,name=async,proto3" json:"async,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *JobRequest) Reset() {
	*x = JobRequest{}
	mi := &file_job_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobRequest) ProtoMessage() {}

func (x *JobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobRequest.ProtoReflect.Descriptor instead.
func (*JobRequest) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{0}
}

func (x *JobRequest) GetSubmitterAgentId() string {
	if x != nil {
		return x.SubmitterAgentId
	}
	return ""
}

func (x *JobRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *JobRequest) GetLlm() *LLMInferencePayload {
	if x != nil {
		return x.Llm
	}
	return nil
}

func (x *JobRequest) GetAsync() bool {
	if x != nil {
		return x.Async
	}
	return false
}

type LLMInferencePayload struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Model             string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Prompt            string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	MaxTokens         int32                  `protobuf:"varint,3,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	Temperature       float32                `protobuf:"fixed32,4,opt,name=temperature,proto3" json:"temperature,omitempty"`
	RequiredGpuLayers int32                  `protobuf:"varint,5,opt,name=required_gpu_layers,json=requiredGpuLayers,proto3" json:"required_gpu_layers,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LLMInferencePayload) Reset() {
	*x = LLMInferencePayload{}
	mi := &file_job_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMInferencePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMInferencePayload) ProtoMessage() {}

func (x *LLMInferencePayload) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMInferencePayload.ProtoReflect.Descriptor instead.
func (*LLMInferencePayload) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{1}
}

func (x *LLMInferencePayload) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *LLMInferencePayload) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *LLMInferencePayload) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *LLMInferencePayload) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *LLMInferencePayload) GetRequiredGpuLayers() int32 {
	if x != nil {
		return x.RequiredGpuLayers
	}
	return 0
}

type JobHandle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobHandle) Reset() {
	*x = JobHandle{}
	mi := &file_job_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobHandle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobHandle) ProtoMessage() {}

func (x *JobHandle) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobHandle.ProtoReflect.Descriptor instead.
func (*JobHandle) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{2}
}

func (x *JobHandle) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobHandle) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type JobStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	JobId           string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status          string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	AssignedAgentId string                 `protobuf:"bytes,3,opt,name=assigned_agent_id,json=assignedAgentId,proto3" json:"assigned_agent_id,omitempty"`
	Result          []byte                 `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	Error           string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CompletedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	TokenCost       float32                `protobuf:"fixed32,8,opt,name=token_cost,json=tokenCost,proto3" json:"token_cost,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *JobStatus) Reset() {
	*x = JobStatus{}
	mi := &file_job_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatus) ProtoMessage() {}

func (x *JobStatus) ProtoReflect() protoreflect.Message {
	mi := &file_job_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatus.ProtoReflect.Descriptor instead.
func (*JobStatus) Descriptor() ([]byte, []int) {
	return file_job_proto_rawDescGZIP(), []int{3}
}

func (x *JobStatus) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobStatus) GetAssignedAgentId() string {
	if x != nil {
		return x.AssignedAgentId
	}
	return ""
}

func (x *JobStatus) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *JobStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *JobStatus) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *JobStatus) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *JobStatus) GetTokenCost() float32 {
	if x != nil {
		return x.TokenCost
	}
	return 0
}

var File_job_proto protoreflect.FileDescriptor

const file_job_proto_rawDesc = "" +
	"\n" +
	"\tjob.proto\x12\x10sharedgpu.job.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9d\x01\n" +
	"\n" +
	"JobRequest\x12,\n" +
	"\x12submitter_agent_id\x18\x01 \x01(\tR\x10submitterAgentId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x127\n" +
	"\x03llm\x18\x03 \x01(\v2%.sharedgpu.job.v1.LLMInferencePayloadR\x03llm\x12\x14\n" +
	"\x05async\x18\x04 \x01(\bR\x05async\"\xb4\x01\n" +
	"\x13LLMInferencePayload\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x03 \x01(\x05R\tmaxTokens\x12 \n" +
	"\vtemperature\x18\x04 \x01(\x02R\vtemperature\x12.\n" +
	"\x13required_gpu_layers\x18\x05 \x01(\x05R\x11requiredGpuLayers\"]\n" +
	"\tJobHandle\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xad\x02\n" +
	"\tJobStatus\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12*\n" +
	"\x11assigned_agent_id\x18\x03 \x01(\tR\x0fassignedAgentId\x12\x16\n" +
	"\x06result\x18\x04 \x01(\fR\x06result\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\fcompleted_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12\x1d\n" +
	"\n" +
	"token_cost\x18\b \x01(\x02R\ttokenCostBAZ?github.com/lambdawp-567/sharedgpupower/backend/internal/grpc/pbb\x06proto3"

var (
	file_job_proto_rawDescOnce sync.Once
	file_job_proto_rawDescData []byte
)

func file_job_proto_rawDescGZIP() []byte {
	file_job_proto_rawDescOnce.Do(func() {
		file_job_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_job_proto_rawDesc), len(file_job_proto_rawDesc)))
	})
	return file_job_proto_rawDescData
}

var file_job_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_job_proto_goTypes = []any{
	(*JobRequest)(nil),            // 0: sharedgpu.job.v1.JobRequest
	(*LLMInferencePayload)(nil),   // 1: sharedgpu.job.v1.LLMInferencePayload
	(*JobHandle)(nil),             // 2: sharedgpu.job.v1.JobHandle
	(*JobStatus)(nil),             // 3: sharedgpu.job.v1.JobStatus
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_job_proto_depIdxs = []int32{
	1, // 0: sharedgpu.job.v1.JobRequest.llm:type_name -> sharedgpu.job.v1.LLMInferencePayload
	4, // 1: sharedgpu.job.v1.JobHandle.created_at:type_name -> google.protobuf.Timestamp
	4, // 2: sharedgpu.job.v1.JobStatus.created_at:type_name -> google.protobuf.Timestamp
	4, // 3: sharedgpu.job.v1.JobStatus.completed_at:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_job_proto_init() }
func file_job_proto_init() {
	if File_job_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_job_proto_rawDesc), len(file_job_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_job_proto_goTypes,
		DependencyIndexes: file_job_proto_depIdxs,
		MessageInfos:      file_job_proto_msgTypes,
	}.Build()
	File_job_proto = out.File
	file_job_proto_goTypes = nil
	file_job_proto_depIdxs = nil
}
